version: '3.1'

services:
  # --- poke ---
  poke:
    hostname: poke
    restart: always
    build:
      context: poke
      args:
        - PASSWORD=$PASSWORD_10000
    volumes:
      - ../receiver/flags/poke.txt:/flag.txt:ro
      - ../utils/bashrc:/root/.bashrc:ro
      - ../utils/preexec.sh:/root/.preexec.sh:ro
    ports:
      - "10000:80"
      - "10022:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # --- poke ---
